# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: peddadahemanth6@gmail.com
author_name: hemanth4-9
contract_name: vault
deployment_language: python
preset_name: starter
project_name: Vaulttracker-contracts

